AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa Skill https://developer.amazon.com/alexa-skills-kit
Resources:
  AlexaSkillFunction:
    Properties:
      CodeUri:
        Bucket: <bucket>
        Key: sammytest.zip
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Handler: sample.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31