AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CRUD webservice. State is stored in a SimpleTable (DynamoDB) resource.
Resources:
  DeleteFunction:
    Properties:
      CodeUri:
        Bucket: <bucket>
        Key: sammytest.zip
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        DeleteResource:
          Properties:
            Method: delete
            Path: /resource/{resourceId}
          Type: Api
      Handler: index.delete
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
    Type: AWS::Serverless::Function
  GetFunction:
    Properties:
      CodeUri:
        Bucket: <bucket>
        Key: sammytest.zip
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /resource/{resourceId}
          Type: Api
      Handler: index.get
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: python3.6
    Type: AWS::Serverless::Function
  PutFunction:
    Properties:
      CodeUri:
        Bucket: <bucket>
        Key: sammytest.zip
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        PutResource:
          Properties:
            Method: put
            Path: /resource/{resourceId}
          Type: Api
      Handler: index.put
      Policies: AmazonDynamoDBFullAccess
      Runtime: python3.6
    Type: AWS::Serverless::Function
  Table:
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31