AWSTemplateFormatVersion: '2010-09-09'
Description: A hello world application.
Parameters:
  Bucket:
    Type: String
  CodeZipKey:
    Type: String

Resources:
  HelloWorldFunction:
    Properties:
      CodeUri:
        Bucket:
          Ref: Bucket
        Key:
          Ref: CodeZipKey
      Handler: sample.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31